name: RMart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^0.1.2+2
  flutter_icons: ^1.1.0
  cupertino_icons: ^0.1.3
  curved_navigation_bar: ^0.3.3
  responsive_navigation_bar: ^1.2.0+1
  sticky_headers: ^0.1.8
  sembast: ^2.4.7+6
  path_provider: ^1.6.14
  sliding_up_panel: ^1.0.2
  modal_bottom_sheet: ^0.2.0+1
  provider: ^4.3.2+2
  cached_network_image: ^2.3.2+1
  http: ^0.12.2
  qr_flutter: ^3.1.0
  jaguar_jwt: ^2.1.6
  razorpay_flutter: ^1.1.0
  pin_code_fields: ^6.1.0
  socket_io_client: ^0.9.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/Images/mart2.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/Images/icon.png
    - lib/assets/Images/avatar.webp
    - lib/assets/Images/pizza.png
    - lib/assets/Images/Products/burger.png
    - lib/assets/Images/Products/cappuccino.png
    - lib/assets/Images/Products/Chappathi.png
    - lib/assets/Images/Products/chocolate-coffee.png
    - lib/assets/Images/Products/cold-coffee.png
    - lib/assets/Images/Products/cup-noodles.png
    - lib/assets/Images/Products/dosa.png
    - lib/assets/Images/Products/fried-rice.png
    - lib/assets/Images/Products/idly.png
    - lib/assets/Images/Products/lays.png
    - lib/assets/Images/Products/manchurian.png
    - lib/assets/Images/Products/mango-juice.png
    - lib/assets/Images/Products/mint-lime.png
    - lib/assets/Images/Products/noodles.png
    - lib/assets/Images/Products/oreo.png
    - lib/assets/Images/Products/paratha.png
    #    - lib/assets/Images/Products/Pasta.png
    - lib/assets/Images/Products/pepsi-can.png
    - lib/assets/Images/Products/pizza.png
    - lib/assets/Images/Products/pongal.png
    - lib/assets/Images/Products/poori.png
    - lib/assets/Images/Products/puff.png
    - lib/assets/Images/Products/samosa.png
    - lib/assets/Images/Products/strawberry-juice.png
    - lib/assets/Images/Products/veg-sandwich.png
    - lib/assets/Images/martLogo.png
    - lib/assets/Images/burger.png
    - lib/assets/Images/foods.png
    - lib/assets/Images/cart.png
    - lib/assets/Images/done.png
    - lib/assets/Images/failed.png
    - lib/assets/Images/Categories/lunch.png
    - lib/assets/Images/Categories/Others.png
    - lib/assets/Images/Categories/juices.png
    - lib/assets/Images/Categories/Coffees.png
    - lib/assets/Images/Categories/breakfast.png
    - lib/assets/Images/Categories/snacks.png
    - lib/assets/Images/Categories/soft drinks.png
    - lib/assets/Images/razorpay.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/Fonts/Poppins/Poppins-Black.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-Bold.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-Italic.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-Light.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-LightItalic.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-Medium.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-Regular.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-SemiBold.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-Thin.ttf
        - asset: lib/assets/Fonts/Poppins/Poppins-ThinItalic.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
